package space.kscience.controls.api.messages

import kotlinx.serialization.Polymorphic
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import space.kscience.controls.api.addressing.Address
import space.kscience.controls.api.data.RawValue
import space.kscience.dataforge.meta.Meta
import space.kscience.dataforge.meta.get
import space.kscience.dataforge.meta.string
import space.kscience.dataforge.names.Name
import kotlin.time.Instant

/**
 * The fundamental contract for all messages flowing through the distributed control system.
 */
@Polymorphic
public interface DeviceMessage {
    /**
     * The network-wide address of the sender.
     */
    public val source: Address

    /**
     * The timestamp of message creation.
     * This time is used for causal ordering and time-series logging.
     */
    public val time: Instant

    /**
     * The optional target address.
     * If `null`, the message is considered a broadcast or is directed to the parent Hub.
     */
    public val target: Address?

    /**
     * Context-specific metadata for infrastructure layers.
     */
    public val attributes: Meta
}

/**
 * A standard implementation for generic system errors.
 *
 * Used for reporting crashes, driver failures, or validation errors during message processing.
 *
 * @property errorType A string identifier for the error category (e.g. "ValidationFault", "Timeout").
 * @property message Human-readable error description.
 * @property stackTrace Optional stack trace for debugging.
 */
@Serializable
@SerialName("device.error")
public data class DeviceErrorMessage(
    override val source: Address,
    override val time: Instant,
    val errorType: String,
    val message: String,
    val stackTrace: String? = null,
    override val target: Address? = null,
    override val attributes: Meta = Meta.EMPTY
) : DeviceMessage

/**
 * Telemetry event carrying a property change.
 * Generated by the QoS Controller.
 */
@Serializable
@SerialName("event.property")
public data class PropertyChangedEvent(
    override val source: Address,
    override val time: Instant,
    val property: Name,
    val value: RawValue,
    override val target: Address? = null,
    override val attributes: Meta = Meta.EMPTY
) : DeviceMessage

/**
 * Retrieves the Request ID from the message attributes, if present.
 * Used for RPC-style communication patterns.
 */
public val DeviceMessage.requestId: String?
    get() = attributes["requestId"]?.string

/**
 * Retrieves the Correlation ID from the message attributes, if present.
 * Used for distributed tracing.
 */
public val DeviceMessage.correlationId: String?
    get() = attributes["correlationId"]?.string