[versions]
# Core Framework
kscience-tools = "0.20.2-kotlin-2.3.0"
atomicfu = "0.30.0-beta"
dataforge = "0.10.2"
kstatemachine = "0.35.0"
kotlinx-datetime = "0.7.1-0.6.x-compat"
kotlinx-coroutines = "1.10.2"
ktor = "3.3.3"
okio = "3.16.4"
kotlinx-io-core = "0.8.2"
sqldelight = "2.2.1"
attributes-kt = "0.4.0"

# RSocket
rsocket = "0.20.0"

# Persistence & IO
xodus = "2.0.1"
jSerialComm = { module = "com.fazecast:jSerialComm", version = "2.11.2" }
kmongo = "5.5.1"
hivemq = "1.3.10"
rabbitmq = "5.27.1"

# Integration & Drivers
j2mod = "3.3.0"
milo = "1.0.2"
pi4j = "3.0.2"
pi4j-ktx = "2.4.0"
plc4j = "0.13.1"

# UI & Visualization
visionforge = "0.5.0"
tornadofx = "1.7.20"
koala-plots = "0.10.2"

# Testing
logback = "1.5.23"
testcontainers = "2.0.3"
uuid = "0.8.4"

# Gradle Plugins
ben-manes-versions = "0.53.0"
version-catalog-update = "1.0.1"
foojay-resolver = "1.0.0"

[libraries]
# DataForge
dataforge-io = { module = "space.kscience:dataforge-io", version.ref = "dataforge" }
dataforge-meta = { module = "space.kscience:dataforge-meta", version.ref = "dataforge" }
dataforge-context = { module = "space.kscience:dataforge-context", version.ref = "dataforge" }
dataforge-data = { module = "space.kscience:dataforge-data", version.ref = "dataforge" }

# kscience
kscience-gradle-tools = { module = "space.kscience:gradle-tools", version.ref = "kscience-tools" }
attributes-kt = { module = "space.kscience:attributes-kt", version.ref = "attributes-kt" }
attributes-kt-serialization = { module = "space.kscience:attributes-kt-serialization", version.ref = "attributes-kt" }

# KotlinX
kotlinx-atomicfu = { module = "org.jetbrains.kotlinx:atomicfu", version.ref = "atomicfu" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinx-datetime" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinx-coroutines" }
kotlinx-io-core = { module = "org.jetbrains.kotlinx:kotlinx-io-core", version.ref = "kotlinx-io-core" }

# KStateMachine
kstatemachine-core = { module = "io.github.nsk90:kstatemachine", version.ref = "kstatemachine" }
kstatemachine-coroutines = { module = "io.github.nsk90:kstatemachine-coroutines", version.ref = "kstatemachine" }
kstatemachine-serialization = { module = "io.github.nsk90:kstatemachine-serialization", version.ref = "kstatemachine" }

# Ktor
ktor-server-core = { module = "io.ktor:ktor-server-core-jvm", version.ref = "ktor" }
ktor-server-netty = { module = "io.ktor:ktor-server-netty-jvm", version.ref = "ktor" }
ktor-network = { module = "io.ktor:ktor-network", version.ref = "ktor" }
ktor-client-websockets = { module = "io.ktor:ktor-client-websockets", version.ref = "ktor" }
rsocket-ktor-client = { module = "io.rsocket.kotlin:ktor-client-rsocket", version.ref = "rsocket" }
rsocket-transport-ktor-tcp = { module = "io.rsocket.kotlin:rsocket-transport-ktor-tcp", version.ref = "rsocket" }

# Okio
okio = { module = "com.squareup.okio:okio", version.ref = "okio" }
okio-fakefilesystem = { module = "com.squareup.okio:okio-fakefilesystem", version.ref = "okio" }
okio-nodefilesystem = { module = "com.squareup.okio:okio-nodefilesystem", version.ref = "okio" }
okio-wasifilesystem = { module = "com.squareup.okio:okio-wasifilesystem", version.ref = "okio" }

# Other
uuid = { module = "com.benasher44:uuid", version.ref = "uuid" }
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
xodus-entity-store = { module = "org.jetbrains.xodus:xodus-entity-store", version.ref = "xodus" }
tornadofx = { module = "no.tornado:tornadofx", version.ref = "tornadofx" }
hivemq-mqtt-client = { module = "com.hivemq:hivemq-mqtt-client", version.ref = "hivemq" }
rabbitmq-amqp-client = { module = "com.rabbitmq:amqp-client", version.ref = "rabbitmq" }
j2mod = { module = "com.ghgande:j2mod", version.ref = "j2mod" }
kmongo-coroutine-serialization = { module = "org.litote.kmongo:kmongo-coroutine-serialization", version.ref = "kmongo" }
milo-client = { module = "org.eclipse.milo:milo-sdk-client", version.ref = "milo" }
pi4j-ktx = { module = "com.pi4j:pi4j-ktx", version.ref = "pi4j-ktx" }
plc4j-spi = { module = "org.apache.plc4x:plc4j-spi", version.ref = "plc4j" }
visionforge-server = { module = "space.kscience:visionforge-server", version.ref = "visionforge" }
koalaplot-core = { module = "io.github.koalaplot:koalaplot-core", version.ref = "koala-plots" }
testcontainers-core = { module = "org.testcontainers:testcontainers", version.ref = "testcontainers" }

sqldelight-gradle = { module = "app.cash.sqldelight:gradle-plugin", version.ref = "sqldelight" }
sqldelight-driver-sqlite = { module = "app.cash.sqldelight:sqlite-driver", version.ref = "sqldelight" }
sqldelight-driver-native = { module = "app.cash.sqldelight:native-driver", version.ref = "sqldelight" }
sqldelight-driver-jdbc-sqlite = { module = "app.cash.sqldelight:jdbc-driver", version.ref = "sqldelight" }
sqldelight-driver-sqljs = { module = "app.cash.sqldelight:sqljs-driver", version.ref = "sqldelight" }
sqldelight-runtime = { module = "app.cash.sqldelight:runtime", version.ref = "sqldelight" }
sqldelight-coroutines = { module = "app.cash.sqldelight:coroutines-extensions", version.ref = "sqldelight" }

[plugins]
# KotlinX
kotlinx-atomicfu = { id = "org.jetbrains.kotlinx.atomicfu", version.ref = "atomicfu" }

# KScience
kscience-project = { id = "space.kscience.gradle.project", version.ref = "kscience-tools" }
kscience-mpp = { id = "space.kscience.gradle.mpp", version.ref = "kscience-tools" }
kscience-jvm = { id = "space.kscience.gradle.jvm", version.ref = "kscience-tools" }
kscience-js = { id = "space.kscience.gradle.js", version.ref = "kscience-tools" }

# Build tools
ben-manes-versions = { id = "com.github.ben-manes.versions", version.ref = "ben-manes-versions" }
version-catalog-update = { id = "nl.littlerobots.version-catalog-update", version.ref = "version-catalog-update" }

sqldelight = { id = "app.cash.sqldelight", version.ref = "sqldelight" }
