package space.kscience.krig.ksp

internal fun generatedKotlinFile(
    outputPackage: String,
    imports: List<String>,
    body: StringBuilder.() -> Unit,
): String = buildString {
    appendLine("// Generated by krig-ksp-processor - do not edit")
    appendLine("@file:Suppress(\"unused\")")
    appendLine()
    appendLine("package $outputPackage")
    appendLine()
    imports.forEach { appendLine("import $it") }
    appendLine()
    body()
}
